### ISSUE TITLE
No packages in the repo

### ISSUE THREAD

**Issue by peppelorum** [mrward/monodevelop-paket-addin#7]
Hi!

Followed the instructions and added the alpha channel, hit refresh, but can't find any package at all at that channel, is it me or is something broken?

Best regards
Peppe

**Comment by mrward** [comment]
What version of Xamarin Studio are you using?

**Comment by mrward** [comment]
You can also find downloads of the Paket addin from [GitHub](https://github.com/mrward/monodevelop-addins/tree/gh-pages). The folders are the versions of Xamarin Studio that they support.

**Comment by peppelorum** [comment]
Ah, sorry, 6.1.3.
I will see how I can install the addins manually.

Thanks! =)

**Comment by mrward** [comment]
Not sure what is going on with the addin server. With the 6.1.3 addin repository url the list of addins is incomplete. If I add a new adding repository url using 6.1 I can see the Paket addin.

  http://addins.monodevelop.com/Beta/Mac/6.1/main.mrep

You could try adding the above url to the Add-in Manager dialog.

I publish the addins to GitHub anyway because of problems that sometimes affect the main MonoDevelop repository.

 To install it manually download the .mpack. Then in the Add-in Manager select the Install from file button.

**Comment by peppelorum** [comment]
Thanks a lot! =)
